#include <stdio.h>
#include <string.h>
#include <time.h>
#include <stdarg.h>
#include "hruby_sim.h"


/**
 *  The HDLRuby simulation mute output engine, to be used with C code
 *  generated by the csim engine or by the rcsim engine. 
 **/

/* Global variables storing the configuration of the vcd generation. */



/* Low-end print functions. */

/** Prints the time.
 *  @param time the time to show (given in ps). */
static void mute_print_time(unsigned long long time) {
}

/** Prints the name of an object without its hierarchy.
 *  @param object the object to print the name. */
static void mute_print_name(Object object) {
}

/** Prints the full name of an object without its hierarchy.
 *  @param object the object to print the name. */
static void mute_print_full_name(Object object) {
}

/** Prints a value.
 *  @param value the value to print */
static void mute_print_value(Value value) {
}

/** Prints a signal with its future value if any.
 *  @param signal the signal to show */
static void mute_print_signal_fvalue(SignalI signal) {
}

/** Prints a signal with its current value if any
 *  @param signal the signal to show */
static void mute_print_signal_cvalue(SignalI signal) {
}



/* The configuration and initialization of the vcd vizualizer. */


/** Sets up the mute vizualization engine.
 *  @param name the name of the vizualization. */
extern void init_mute_visualizer(char* name) {
    /* Initialize the vizualizer printer engine. */
    init_visualizer(&mute_print_time,
                    &mute_print_full_name,
                    &mute_print_value,
                    &mute_print_signal_fvalue,
                    &default_print_string,
                    &default_print_name,
                    &default_print_value);
}
