#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include "hruby_sim.h"


/**
 *  The HDLRuby pool used for quickly getting empty values, to be used 
 *  with C code generated by hruby_low2c. 
 **/

static ValueS* pool_values = NULL;
static unsigned int pool_cap = 0; /* The capacity of the pool. */
static unsigned int pool_pos = 0; /* The position in the pool. */

/** Get a fresh value. */
Value get_value() {
    if (pool_pos == pool_cap) {
        /* Need to increase the pool capacity. */
        pool_cap = pool_cap == 0 ? 16 : pool_cap * 2;
        pool_values = (ValueS*)realloc(pool_values,pool_cap*sizeof(ValueS));
        /* Clears the new values. */
        memset(&(pool_values[pool_pos]),0,(pool_cap-pool_pos)*sizeof(ValueS));
    }
    /* Readjust the position in the pool and return the value. */
    return &(pool_values[pool_pos++]);
}

/** Frees the last value of the pool. */
void free_value() {
    if (pool_pos > 0) pool_pos--;
}

/** Gets the current state of the value pool. */
unsigned int get_value_pos() {
    return pool_pos;
}

/** Restores the state of the value pool.
 *  @param pos the new position in the pool */
void set_value_pos(unsigned int pos) {
    pool_pos = pos;
}
