#include <stdio.h>
#include <string.h>
#include <time.h>
#include <stdarg.h>
#include "hruby_sim.h"


/**
 *  The HDLRuby simulation vcd format genertion engine, to be used with C code
 *  generated by hruby_low2c. 
 **/

/* Global variables storing the configuration of the vcd generation. */

/* The target file. */
static FILE* vcd_file;

/* The time scale unit in the ps. */
static unsigned long long vcd_timeunit = 1;

/* Accessing target file. */

/** Prints to the vcd file.
 *  @param fmt the format for handling the variadic arguments. */
static int vcd_print(char* fmt, ...) {
    int ret;

    /* Declare a va_list type variable */
    va_list myargs;

    /* Initialise the va_list variable with the ... after fmt */
    va_start(myargs, fmt);

    /* Forward the '...' to vprintf */
    ret = vfprintf(vcd_file, fmt, myargs);

    /* Clean up the va_list */
    va_end(myargs);

    return ret;
}


/* Utility functions for printing in vcd format. */

/* Replace all the occurences of a character with another. 
 * CREDIT: Superlokkus */
static char* replace_char(char* str, char find, char replace){
    char *current_pos = strchr(str,find);
    while (current_pos){
        *current_pos = replace;
        current_pos = strchr(current_pos+1,find);
    }
    return str;
}


/* Low-end print functions. */

/** Prints the time.
 *  @param time the time to show (given in ps). */
static void vcd_print_time(unsigned long long time) {
    vcd_print("#%llu\n",time/vcd_timeunit);
}


/** Prints the name of an object.
 *  @param object the object to print the name. */
static void vcd_print_name(Object object) {
    /* Recurse on the owner if any. */
    // printf("owner=%p\n",object->owner);
    if (object->owner != NULL) {
        vcd_print_name(object->owner);
        vcd_print("$");
    }
    /* Depending on the kind of object. */
    switch(object->kind) {
        case SYSTEMT:
        case SIGNALI:
        case SCOPE:
        case SYSTEMI:
            /* Print the name if name. */
            /* Trick: SystemT, SignalI, Scope and SystemI have the
             * field name at the same place. */
            if (((SystemI)object)->name != NULL) {
                char name[256];
                strncpy(name,((SystemI)object)->name,256);
                replace_char(name,':','$');
                vcd_print("%s",name);
            }
        default: /* Nothing to do */
            break;
    }
}

/** Prints a value.
 *  @param value the value to print */
static void vcd_print_value(Value value) {
    vcd_print("b");
    if (value->numeric) {
        unsigned long long width = type_width(value->type);
        unsigned long long mask = 1ULL << (width-1);
        for(; mask > 0; mask >>= 1) {
            vcd_print("%d",(value->data_int & mask) != 0);
        }
    } else {
        /* Display a bitstring value. */
        int i;
        int width = type_width(value->type);
        char* data = value->data_str;
        if (value->capacity == 0) {
            /* The value is empty, therefore undefined. */
            for(i=width; i>0; --i) {
                vcd_print("u");
            }
        }
        else {
            /* The value is not empty. */
            for(i=width; i>0; --i) {
                vcd_print("%c",data[i-1]);
            } 
        }
    }
}

/** Prints a signal declaration.
 *  @param signal the signal to declare */
static void vcd_print_var(SignalI signal) {
    vcd_print("$var wire %d ",type_width(signal->type));
    vcd_print_name((Object)signal);
    vcd_print(" ");
    vcd_print_name((Object)signal);
    vcd_print(" $end\n");
}


/** Prints a signal.
 *  @param signal the signal to show */
static void vcd_print_signal(SignalI signal) {
    vcd_print_value(signal->f_value);
    vcd_print(" ");
    vcd_print_name((Object)signal);
    vcd_print("\n");
}




/* high-end print functions. */

/** Prints the header of the vcd file. */
static void vcd_print_header() {
    /* The date section. */
    vcd_print("$date\n");
    {
        char text[100];
        time_t now = time(NULL);
        struct tm *t = localtime(&now);
        strftime(text, sizeof(text), "%d %m %Y %H:%M", t);
        vcd_print("   %s\n", text);
    }
    vcd_print("$end\n");

    /* The version section. */
    vcd_print("$version\n");
    vcd_print("   Generated from HDLRuby simulator\n");
    vcd_print("$end");
    
    /* The comment section. */
    vcd_print("$comment\n");
    vcd_print("   Is it an easter egg?\n");
    vcd_print("$end\n");

    /* The time scale section: for now 1ps only. */
    vcd_print("$timescale 1ps $end\n");

    /* The scope section: nothing specific. */
    vcd_print("$scope module logic $end\n");

    /* The variables declaration. */
    each_all_signal(&vcd_print_var);

    /* Ends the declarations. */
    vcd_print("$upscope $end\n");
    vcd_print("$enddefinitions $end\n");

    /* Display the initializations. */
    vcd_print("$dumpvars\n");
    // Maybe nothing to do.
    // each_all_init_signal(&vcd_print_signal);
    vcd_print("$end\n");
}


/* The configuration and initialization of the vcd vizualizer. */


/** Sets up the vcd vizualization engine.
 *  @param name the name of the vizualization. */
extern void init_vcd_visualizer(char* name) {
    /* Open the resulting file with name: <name>.vcd */
    char filename[256];
    strncpy(filename,name,256);
    strncat(filename,".vcd",256);
    vcd_file = fopen(filename,"w");

    /* Initialize the vizualizer printer engine. */
    init_visualizer(&vcd_print_time,
                    &vcd_print_name,
                    &vcd_print_value,
                    &vcd_print_signal);

    /* Prints the header of the vcd file. */
    vcd_print_header();
}
