#include <stdio.h>
#include "hruby_sim.h"


/**
 *  The HDLRuby simulation visualization engine, to be used with C code
 *  generated by hruby_low2c. 
 **/

/** Prints the time.
 *  @param time the time to show. */
void print_time(unsigned long long time) {
    printf("# %lluns",time);
}

/** Prints the time and goes to the next line.
 *  @param time the time to show. */
void println_time(unsigned long long time) {
    print_time(time);
    printf("\n");
}

/** Prints the name of an object.
 *  @param object the object to print the name. */
void print_name(Object object) {
    /* Recurse on the owner if any. */
    // printf("owner=%p\n",object->owner);
    if (object->owner != NULL) {
        print_name(object->owner);
        printf("::");
    }
    /* Depending on the kind of object. */
    switch(object->kind) {
        case SYSTEMT:
        case SIGNALI:
        case SCOPE:
        case SYSTEMI:
            /* Print the name if name. */
            /* Trick: SystemT, SignalI, Scope and SystemI have the
             * field name at the same place. */
            if (((SystemI)object)->name != NULL) {
                printf("%s",((SystemI)object)->name);
            }
        default: /* Nothing to do */
            break;
    }
}

/** Prints a value.
 *  @param value the value to print */
void print_value(Value value) {
    int i;
    int size = value->size;
    unsigned int* data = value->data;
    if (data == NULL) {
        /* The value is not defined yet. */
        for(i=size; i>0; --i) {
            printf("UUUU");
        }
    } else for(i=size; i>0; --i) {
        printf("%04x",data[i-1]);
    }
}

/** Prints a signal.
 *  @param signal the signal to show */
void print_signal(SignalI signal) {
    print_name((Object)signal);
    printf(": ");
    print_value(signal->f_value);
}

/** Prints a signal and goes to the next line.
 *  @param signal the signal to show */
void println_signal(SignalI signal) {
    print_signal(signal);
    printf("\n");
}
